version: 0.2

env:
  variables:
    LC_ALL: en_US.UTF-8
    LANGUAGE: en_US.UTF-8
    LANG: en_US.UTF-8

phases:
  build:
    commands:
      - echo Running build
      - rake build 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Deploying to S3
      - rake deploy
artifacts:
  base-directory: _site
  files:
    - '**/*'
  name: ronnieeichler-$(date +%Y-%m-%d-%H-%M-%S) 