version: 0.2

env:
  variables:
    LC_ALL: en_US.UTF-8
    LANGUAGE: en_US.UTF-8
    LANG: en_US.UTF-8

phases:
  install:
    commands:
      - echo Generate locale
      - locale-gen en_US.UTF-8
      - echo Install nodejs
      - apt-get update && apt-get install -y nodejs
      - echo Installing gems
      - bundle install
  build:
    commands:
      - echo Running build
      - rake build 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory: _site
  files:
    - '**/*'
  